[project]
name = "recommendation-system"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.26.0,<1.27.0",
    "pyarrow>=10.0.0",
    "bloom-filter2>=2.0.0",
    "tensorflow==2.15.1",
    "optuna>=3.0.0",
]
